version: '3.7'

services:
  api01: &api
    image: rochajg/rinhav2:latest
    hostname: api01
    container_name: api01
    restart: always
    ports:
      - "8081:8080"
    environment:
      MONGO_HOST: db
      MONGO_PORT: 27017
    depends_on:
      mongodb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "220MB"

  api02:
    <<: *api
    hostname: api02
    container_name: api02
    ports:
      - "8082:8080"

  nginx:
    image: nginx:stable-perl
    container_name: nginx
    restart: always
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.14"
          memory: "10MB"

  mongodb:
    image: mongo:7-jammy
    container_name: mongodb
    hostname: db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: rinhav2
    ports:
      - "27017:27017"
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/rinhav2 --quiet
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "100MB"

networks:
  default:
    driver: bridge
    name: rinhav2
