micronaut:
  application:
    name: rinhav2
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASS}
    dialect: POSTGRESQL
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?maxLifetime=300000
    pool:
      max-size: 10
      min-size: 1

jpa:
  default:
    properties:
      hibernate:
        show_sql: true

jackson:
  property-naming-strategy: SNAKE_CASE
  serialization:
    writeDatesAsTimestamps: false
  serialization-inclusion: non_absent

